server {
    listen 80;

    # Serve static frontend files from this directory
    root /usr/share/nginx/html;
    index index.html;

    # For any route, serve index.html (handles browser refresh)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy all /api calls to the backend Kubernetes service
    # 'backend-service' is the K8s Service name we will create
    # Port 5000 is where our Node.js app listens
    location /api {
        proxy_pass http://backend-service:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
# 👉 Nginx serves UI and forwards /api to backend


# / → UI
# /api → backend


# "When a user accesses the application, Nginx serves the frontend index.html. Once the page loads, JavaScript executes and makes API calls like /api/todos. These requests are first received by Nginx, which proxies them to the backend service. The backend processes the request, interacts with the database, and returns a response, which is then rendered by the frontend."Browser ALWAYS talks to Nginx (not backend directly)

# User hits URL
# → Nginx (nginx.conf) serves index.html
# Frontend loads
# → JavaScript in index.html runs
# → Calls /api/todos
# Nginx intercepts /api
# → Proxies to backend (backend-service:5000)
# Backend flow
# index.js → entry point
# routes → todos.js
# model → Todo.js
# DB → MongoDB
# Response comes back
# → frontend updates UI (renderTodos())

# User → http://app-server
#        ↓
# Nginx → serves index.html
#        ↓
# Frontend JS runs
#        ↓
# fetch('/api/todos')
#        ↓
# Nginx → location /api
#        ↓
# backend-service:5000
#        ↓
# Express (index.js)
#        ↓
# Routes (todos.js)
#        ↓
# MongoDB
#        ↓
# Response
#        ↓
# Frontend renders UI